// Scans YourBots/ and prompt/jobs/ and writes the two generated files the
// engine imports. Runs before every `wrangler dev` and `wrangler deploy`
// (build.command in wrangler.jsonc), and on the Deploy button. Because of this
// file, adding a bot is "copy a folder", adding data is "drop a file", and
// nobody edits code.
import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";

const TEXT = /\.(md|txt|csv)$/i;
// APPROVED.txt is the library's override list (see Engine/scripts/sync-library.mjs), not knowledge.
const NOT_KNOWLEDGE = /^approved\.txt$/i;
const ident = (s) => "f_" + s.replace(/[^a-zA-Z0-9]/g, "_");
const isDir = (p) => existsSync(p) && statSync(p).isDirectory();
const listText = (dir) => (isDir(dir) ? readdirSync(dir).filter((f) => TEXT.test(f) && !f.startsWith(".") && !NOT_KNOWLEDGE.test(f)).sort() : []);
// Anything else in knowledge/ (PDF, Word, sheets, images, a library/ subfolder) is the
// library's job — synced to AI Search by the GitHub Action, not bundled here.
const listDocs = (dir) => (isDir(dir) ? readdirSync(dir).filter((f) => !f.startsWith(".") && !TEXT.test(f) && !NOT_KNOWLEDGE.test(f)) : []);

// ---- YourBots/ → YourBots/index.js ----
// Sidebar order: "order" in project.json (lowest first), then name. Folders starting with _ or . are skipped.
// Every kind is listed: "kind": "chat" (default) or "food" (an app at /apps/<id>) — Engine/worker/projects.js.
const bots = readdirSync("YourBots").filter((d) => isDir(join("YourBots", d)) && !d.startsWith("_") && !d.startsWith(".") && existsSync(join("YourBots", d, "project.json")))
  .map((d) => { let o = 100; try { o = Number(JSON.parse(readFileSync(join("YourBots", d, "project.json"), "utf8")).order ?? 100); } catch {} return { d, o }; })
  .sort((a, b) => a.o - b.o || a.d.localeCompare(b.d)).map((x) => x.d);
let imports = [], entries = [];
for (const id of bots) {
  const base = join("YourBots", id);
  const meta = JSON.parse(readFileSync(join(base, "project.json"), "utf8"));
  const v = ident(id);
  imports.push(`import ${v}_meta from "./${id}/project.json";`);
  const hasInstr = existsSync(join(base, "instructions.md"));
  if (hasInstr) imports.push(`import ${v}_instructions from "./${id}/instructions.md";`);
  const files = listText(join(base, "knowledge"));
  files.forEach((f, i) => imports.push(`import ${v}_k${i} from "./${id}/knowledge/${f}";`));
  const overrides = listText(join(base, "prompt"));
  overrides.forEach((f, i) => imports.push(`import ${v}_p${i} from "./${id}/prompt/${f}";`));
  const jobOverrides = listText(join(base, "prompt", "jobs"));
  jobOverrides.forEach((f, i) => imports.push(`import ${v}_j${i} from "./${id}/prompt/jobs/${f}";`));
  entries.push(`  ${JSON.stringify(id)}: project(${v}_meta, ${hasInstr ? `${v}_instructions` : '""'}, {
${files.map((f, i) => `    ${JSON.stringify(f)}: ${v}_k${i},`).join("\n")}
  }, {
${overrides.map((f, i) => `    ${JSON.stringify(f)}: ${v}_p${i},`).join("\n")}${jobOverrides.map((f, i) => `\n    ${JSON.stringify("jobs/" + f)}: ${v}_j${i},`).join("")}
  }),`);
  const docs = listDocs(join(base, "knowledge"));
  const kind = String(meta.kind || "chat");
  console.log(`${kind === "chat" ? "bot" : "app"} ${id.padEnd(20)} ${kind !== "chat" ? `kind: ${kind}  → /apps/${id}  ` : ""}files: ${files.length}${docs.length ? `  library docs: ${docs.length} (synced by the Sync library action, not bundled)` : ""}${overrides.length || jobOverrides.length ? `  own prompt files: ${[...overrides, ...jobOverrides.map((f) => "jobs/" + f)].join(", ")}` : ""}${meta.name ? "" : "  ⚠ no name in project.json"}`);
}
writeFileSync("YourBots/index.js", `// GENERATED by Engine/scripts/discover.mjs — do not edit. Add a bot: copy a folder in
// YourBots/. Add data: drop a .md/.txt/.csv into its knowledge/. Give it its own
// voice: copy a file from YourBots/_prompt/ into its prompt/. Then commit.
${imports.join("\n")}

export const PROJECTS = {
${entries.join("\n")}
};

function stripComments(t) { return String(t || "").replace(/<!--[\\s\\S]*?-->/g, "").trim(); }

function project(meta, instructions, files, promptOverrides) {
  return {
    ...meta,
    starters: Array.isArray(meta.starters) ? meta.starters.slice(0, 4) : [],
    allowedLinks: Array.isArray(meta.allowedLinks) ? meta.allowedLinks : [],
    instructions: stripComments(instructions),
    files: Object.fromEntries(Object.entries(files || {}).map(([n, t]) => [n, stripComments(t)]).filter(([, t]) => t.length > 0)),
    prompt: Object.fromEntries(Object.entries(promptOverrides || {}).map(([n, t]) => [n, stripComments(t)])),
  };
}

export function getProject(id, fallbackId) {
  return PROJECTS[id] || PROJECTS[fallbackId] || Object.values(PROJECTS)[0];
}

export function listProjects() {
  return Object.entries(PROJECTS).map(([id, p]) => ({
    id, kind: typeof p.kind === "string" ? p.kind : "chat", order: Number(p.order ?? 100), name: p.name, tagline: p.tagline || "", greeting: p.greeting || "", starters: p.starters, mode: p.mode, grounding: p.grounding,
    thinkingWords: Array.isArray(p.thinkingWords) && p.thinkingWords.length ? p.thinkingWords : undefined,
    tour: p.tour && Array.isArray(p.tour.stops) ? { stops: p.tour.stops.map(String) } : undefined,   // this bot is the guide (Engine/worker/tour.js)
    // who can use it (Engine/worker/access.js): what the bot says, and whether it's in the sidebar. Never accessKey.
    access: typeof p.access === "string" ? p.access : "", listed: p.listed !== false, model: typeof p.model === "string" ? p.model : "",
    demo: p.demo === true,   // a sample bot that ships in the box (YourBots/config.js → demo.bots)
  }));
}
`);

// ---- YourBots/settings.json ----
// The deployment's default and floor, as written by Settings → Commit to GitHub.
// The engine imports it, so it has to exist: an empty one means "config.js decides".
if (!existsSync("YourBots/settings.json")) { writeFileSync("YourBots/settings.json", JSON.stringify({ access: {} }, null, 2) + "\n"); console.log("settings: created YourBots/settings.json (empty — YourBots/config.js → access applies)"); }

// ---- prompt/jobs/ → Engine/worker/jobs.generated.js ----
const jobs = listText("YourBots/_prompt/jobs").filter((f) => f.endsWith(".md"));
writeFileSync("Engine/worker/jobs.generated.js", `// GENERATED by Engine/scripts/discover.mjs — do not edit. Add a job: add a file to YourBots/_prompt/jobs/.
${jobs.map((f, i) => `import j${i} from "../../YourBots/_prompt/jobs/${f}";`).join("\n")}
export const JOB_FILES = {
${jobs.map((f, i) => `  ${JSON.stringify(f.replace(/\.md$/, ""))}: j${i},`).join("\n")}
};
`);
console.log(`jobs: ${jobs.map((f) => f.replace(/\.md$/, "")).join(", ")}`);
console.log(`registry: ${bots.length} bots → YourBots/index.js, ${jobs.length} jobs → Engine/worker/jobs.generated.js`);
